[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "uwl-v2-client"
version = "0.0.1"
authors = [
  { name="Ricardo Daniel Quiroga", email="l2radamanthys@gmail.com" },
]
description = "An unofficial Python client for the WeatherLink v2 API"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "python-dateutil",
]

[tool.setuptools.packages.find]
where = ["src"]